### ISSUE TITLE
Return errors array for hosts we were unable to connect to (ansible)

### ISSUE THREAD

**Issue by dcolebatch** [tidalmigrations/machine_stats#10]
When using ansible: https://github.com/tidalmigrations/machine_stats/blob/master/unix/runner

Would it be possible to return a list of hosts where we were not able to gather facts, ideally with a reason why?

Adding an `errors: []` array to TOTAL_RESULTS would give us a place to store these errors:

https://github.com/tidalmigrations/machine_stats/blob/master/unix/runner#L20
```
TOTAL_RESULTS = {'servers': [], 'errors': []}
```

And then adding an object like the following to the errors array would be very useful:

```
TOTAL_RESULTS['errors'].append({
            'host_name': xxxxx,
            'errors': "Could not connect etc." 
            })     
```

**Comment by fortran01** [comment]
I took a stab in https://github.com/tidalmigrations/machine_stats/pull/11/files
