### ISSUE TITLE
Obsolete dependenvy: dos2unix

### ISSUE THREAD

**Issue by pshevtsov** [tidalmigrations/machine_stats#5]
We use `dos2unix` to remove UTF-8 BOM, but it's no longer needed since Tidal Tools correctly handles files with UTF-8 BOMs.

After some additional checks let's remove that dependency. WDYT @dcolebatch ?

@prees1 we'll need to set up some Windows env to test the integration.

**Comment by dcolebatch** [comment]
I'm all for simplifying the dependency tree 👍   Go for it.

**Comment by prees1** [comment]
There is a branch now - https://github.com/tidalmigrations/machine_stats/tree/pnr/remove-dos2unix  that removes the `dos2unix` dependency. 

It also removes the execution of `tidal sync servers` from the runner, which makes the execution of the script match the current documentation as well. The addition of the `tidal` command was added with the dos2unix support commit.

**Comment by prees1** [comment]
Resolved in the above pull request.
