### ISSUE TITLE
Add CPU Utilization

### ISSUE THREAD

**Issue by dcolebatch** [tidalmigrations/machine_stats#7]
Hi @pshevtsov - users have asked if we could ship CPU utilization out of the box too.  With the understanding that most users only run this once per day, the users were still happy with having some indication of usage.

I found one crude example of capturing CPU via ansible, by shelling out to top, but whatever is clever! 😄 
https://www.quora.com/What-variable-should-I-use-for-checking-the-CPU-usage-of-a-server-in-an-Ansible-playbook

**Comment by pshevtsov** [comment]
I see two options here:

1. Use [`sysstat`](https://github.com/sysstat/sysstat), but that requires installing some additional software on servers which isn't truly _agentless_.
2. There's [`os.getloadavg`](https://docs.python.org/3.5/library/os.html#os.getloadavg) in Python:
>  Return the number of processes in the system run queue averaged over the last 1, 5, and 15 minutes or raises OSError if the load average was unobtainable.
>
> Availability: Unix.

WDYT?

**Comment by dcolebatch** [comment]
Hmm, I like the idea of parsing `top` better than those two ideas, because we are looking for a % of CPU utilization, not a load average.

We also need this for windows in a consistent manner, and some powershell [like this](https://stackoverflow.com/questions/6298941/how-do-i-find-the-cpu-and-ram-usage-using-powershell) could drop into our PS scripts pretty easily.
